config/routes.rb
DefaultInit::Application.routes.draw do
  
  resources :campaigns do
    member do
      get 'choose'
      post 'update_group'
    end
  end

  mount Ckeditor::Engine => '/ckeditor'

  resources :pre_users, only: [:create]
  get 'maps/index'

  get 'auth/:provider/callback', to: 'sessions#create_with_oauth'  
  get 'auth/failure', to:  "home#index"

  get "admins/dashboard", to:  "admins#dashboard", as: 'admin_home'
  get "admins/podio", to:  "admins#podio_info", as: 'podio_info'
  get "admins/podio_item/:item_id", to:  "admins#podio_item", as: 'podio_item'

  get "sessions/new"
  get "home/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "activate/:token" => "users#activate", :as => "activate"

  get "recover_pass" => "sessions#recover_pass", :as => "recover_pass"
  post "send_pass_recovery" => "sessions#send_pass_recovery", :as => "send_pass_recovery"
  get "change_password/:token" => "sessions#change_password", :as => "change_password"
  post "do_change_password" => "sessions#do_change_password", :as => "do_change_password"

  get "unsubscribe/:token" => "sessions#unsubscribe", :as => "unsubscribe"
  get "unsubscribe/:token/:from" => "sessions#unsubscribe", :as => "unsubscribe_from"
  get "contact" => "home#contact", :as => "contact"
  post "send_contact" => "home#send_contact", :as => "send_contact"

  resources :sessions
  resources :users

  get "home" => "home#index", :as => "home"
  root :to => "home#index"

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :users
      get "/log_in" => "users#show"
      post "/log_in" => "users#show"
      post "/sign_up" => "users#create"
    end
  end

end

app/views/admins/dashboard.html.haml
%h1 Admins#dashboard
%p Find me in app/views/admins/dashboard.html.haml

app/views/admins/podio_info.html.haml
.centered-container.big
  .clear
  %h2 
    Listado de datos desde Podio
    %small= "Mostrando 30 resultados de #{@total.to_i}"

  %table.table
    %tr
      %th ID
      %th Patente
      %th Encargado
      %th Contacto
      %th Acciones
    - @cars.each do |r|
      %tr
        %td= r[:app_id].to_i
        %td=  link_to  r[:patente], r[:link], _target: "blank"
        %td= link_to r[:user][:name] + " - " +  r[:user][:relationship], r[:user][:link], _target: "blank"
        %td= r[:contact]
        %td= link_to "ver más", podio_item_path(r[:item_id])

  %br
  .pages
    .pull-right
      - @pages.times do |i|
        =link_to podio_info_path(page: i) do
          %span.page{class: i == @page ? "active" : ""}=i+1

app/views/admins/podio_item.html.haml
.container
  %h4 Datos Generales
  .row.contact-data
    .col-sm-4
      .col-xs-4 ID
      .col-xs-8= @item[:app_id].to_i
      .col-xs-4 Patente
      .col-xs-8= link_to @item[:patente],@item[:link]
    .col-sm-4
      .col-xs-4 Estado
      .col-xs-8= @item[:estado]
      .col-xs-4 Contacto
      .col-xs-8= @item[:contact]
    .col-sm-4
      .col-xs-4 Campañas
      .col-xs-8= @item[:campains].map{|c| c[:name]}.join(", ")
  .podio_data{style: "display:none"}= @item.to_s
  %br
  %h4 Datos Taxistas

  .row
    -@drivers.each do |d|
      .row.contact-data
        .col-sm-1= "ID: #{d[:app_id]}"
        .col-sm-3= link_to "Nombre: #{d[:name]}", d[:link]
        .col-sm-2= "Teléfono: #{d[:phone]}"
        .col-sm-2= "Rut: #{ d[:rut]}"
        .col-sm-4= "Mail: #{ d[:mail]}"
  %br
  %h4 Datos Dueños
  .row
    -@owners.each do |d|
      .row.contact-data
        .col-sm-1= "ID: #{d[:app_id]}"
        .col-sm-3= link_to "Nombre: #{d[:name]}", d[:link]
        .col-sm-2= "Teléfono: #{d[:phone]}"
        .col-sm-2= "Rut: #{ d[:rut]}"
        .col-sm-4= "Mail: #{ d[:mail]}"
  %br
  %h4 Datos Administradores
  .row
    -@administrators.each do |d|
      .row.contact-data
        .col-sm-1= "ID: #{d[:app_id]}"
        .col-sm-3= link_to "Nombre: #{d[:name]}", d[:link]
        .col-sm-2= "Teléfono: #{d[:phone]}"