config/routes.rb
DefaultInit::Application.routes.draw do
  
  resources :campaigns do
    member do
      get 'choose'
      post 'update_group'
    end
  end

  mount Ckeditor::Engine => '/ckeditor'

  resources :pre_users, only: [:create]
  get 'maps/index'

  get 'auth/:provider/callback', to: 'sessions#create_with_oauth'  
  get 'auth/failure', to:  "home#index"

  get "admins/dashboard", to:  "admins#dashboard", as: 'admin_home'
  get "admins/podio", to:  "admins#podio_info", as: 'podio_info'
  get "admins/podio_item/:item_id", to:  "admins#podio_item", as: 'podio_item'

  get "sessions/new"
  get "home/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "activate/:token" => "users#activate", :as => "activate"

  get "recover_pass" => "sessions#recover_pass", :as => "recover_pass"
  post "send_pass_recovery" => "sessions#send_pass_recovery", :as => "send_pass_recovery"
  get "change_password/:token" => "sessions#change_password", :as => "change_password"
  post "do_change_password" => "sessions#do_change_password", :as => "do_change_password"

  get "unsubscribe/:token" => "sessions#unsubscribe", :as => "unsubscribe"
  get "unsubscribe/:token/:from" => "sessions#unsubscribe", :as => "unsubscribe_from"
  get "contact" => "home#contact", :as => "contact"
  post "send_contact" => "home#send_contact", :as => "send_contact"

  resources :sessions
  resources :users

  get "home" => "home#index", :as => "home"
  root :to => "home#index"

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :users
      get "/log_in" => "users#show"
      post "/log_in" => "users#show"
      post "/sign_up" => "users#create"
    end
  end

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /campaigns
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/new
  def choose
    @campaign = Campaign.new
  end

  # GET /campaigns/new
  def update_group
    @campaign = Campaign.new
  end
  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  def create
    @campaign = Campaign.new(campaign_params)

    if @campaign.save
      redirect_to @campaign, notice: 'Campaign was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /campaigns/1
  def update
    if @campaign.update(campaign_params)
      redirect_to @campaign, notice: 'Campaign was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /campaigns/1
  def destroy
    @campaign.destroy
    redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def campaign_params
      params.require(:campaign).permit(:name, :created_by, :started_at, :finished_at, :end_payment_at, :end_instalation_at)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.haml
= form_for @campaign do |f|
  - if @campaign.errors.any?
    #error_explanation
      %h2= "#{pluralize(@campaign.errors.count, "error")} prohibited this campaign from being saved:"
      %ul
        - @campaign.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :created_by
    = f.number_field :created_by
  .field
    = f.label :started_at
    = f.datetime_select :started_at
  .field
    = f.label :finished_at
    = f.datetime_select :finished_at
  .field
    = f.label :end_payment_at
    = f.datetime_select :end_payment_at
  .field
    = f.label :end_instalation_at
    = f.datetime_select :end_instalation_at
  .actions
    = f.submit 'Save'

app/views/campaigns/edit.html.haml
%h1 Editing campaign

= render 'form'

= link_to 'Show', @campaign
\|
= link_to 'Back', campaigns_path

app/views/campaigns/index.html.haml
%h1 Listing campaigns

%table
  %thead
    %tr
      %th Name
      %th Created by
      %th Started at
      %th Finished at
      %th End payment at
      %th End instalation at
      %th
      %th
      %th

  %tbody
    - @campaigns.each do |campaign|
      %tr
        %td= campaign.name
        %td= campaign.created_by
        %td= campaign.started_at
        %td= campaign.finished_at
        %td= campaign.end_payment_at
        %td= campaign.end_instalation_at
        %td= link_to 'Show', campaign
        %td= link_to 'Edit', edit_campaign_path(campaign)
        %td= link_to 'Destroy', campaign, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Campaign', new_campaign_path

app/views/campaigns/new.html.haml
%h1 New campaign

= render 'form'

= link_to 'Back', campaigns_path

app/views/campaigns/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @campaign.name
%p
  %b Created by:
  = @campaign.created_by
%p
  %b Started at:
  = @campaign.started_at
%p
  %b Finished at:
  = @campaign.finished_at
%p
  %b End payment at:
  = @campaign.end_payment_at
%p
  %b End instalation at:
  = @campaign.end_instalation_at

= link_to 'Edit', edit_campaign_path(@campaign)
\|
= link_to 'Back', campaigns_path