config/routes.rb
DefaultInit::Application.routes.draw do
  
  resources :campaigns do
    member do
      get 'choose'
      post 'update_group'
    end
  end

  mount Ckeditor::Engine => '/ckeditor'

  resources :pre_users, only: [:create]
  get 'maps/index'

  get 'auth/:provider/callback', to: 'sessions#create_with_oauth'  
  get 'auth/failure', to:  "home#index"

  get "admins/dashboard", to:  "admins#dashboard", as: 'admin_home'
  get "admins/podio", to:  "admins#podio_info", as: 'podio_info'
  get "admins/podio_item/:item_id", to:  "admins#podio_item", as: 'podio_item'

  get "sessions/new"
  get "home/index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "activate/:token" => "users#activate", :as => "activate"

  get "recover_pass" => "sessions#recover_pass", :as => "recover_pass"
  post "send_pass_recovery" => "sessions#send_pass_recovery", :as => "send_pass_recovery"
  get "change_password/:token" => "sessions#change_password", :as => "change_password"
  post "do_change_password" => "sessions#do_change_password", :as => "do_change_password"

  get "unsubscribe/:token" => "sessions#unsubscribe", :as => "unsubscribe"
  get "unsubscribe/:token/:from" => "sessions#unsubscribe", :as => "unsubscribe_from"
  get "contact" => "home#contact", :as => "contact"
  post "send_contact" => "home#send_contact", :as => "send_contact"

  resources :sessions
  resources :users

  get "home" => "home#index", :as => "home"
  root :to => "home#index"

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :users
      get "/log_in" => "users#show"
      post "/log_in" => "users#show"
      post "/sign_up" => "users#create"
    end
  end

end

app/views/layouts/_footer.html.haml
%footer
  .footer_social
    .copy.col-sm-4.contFtr
      %p
        %strong=t('common.app_name')
        © copyright #{Time.now.year}. All rights reserved
    .other.col-sm-4.contFtr
      Desarollado por Antti Kulppi
    .social.col-sm-4.contFtr
      %ul
        %li.google
          %a{href: '#'}
        %li.facebook
          %a{href: '#'}
        %li.twitter
          %a{href: '#'}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .clear
      %br
    %div{:class => "alert alert-#{name == 'notice' ? "success" : "danger"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav.navbar-nav.btnMenu2int.right
	- if current_user
		%li.imgUser.hidden-xs
			= image_tag current_user.get_image(:thumb), class: "img-circle"
		- if (can? :index, User)
			%li.btnNombre
				= link_to t('common.admin.users'), users_path
		- if (can? :manage, :admin)
			%li.btnNombre
				= link_to "Podio Info", podio_info_path
		%li.btnNombre
			= link_to current_user.to_s, user_path(current_user)

		%li.btnNombre
			= link_to "Home", home_path
		%li.btnsalir 
			= link_to t('common.nav.logout'), log_out_path
	- else
		%li 
			=# link_to 'Contacto', contact_path
		%li.btnNombre 
			= link_to t('common.nav.login'), log_in_path, :class => 'needs-login'

app/views/layouts/_slidemenu.html.haml
%ul.nav.navbar-nav.btnMenu2int
	- if current_user
		%li.imgUser.hidden-xs
			= image_tag current_user.get_image(:thumb), class: "img-circle"
		- if (can? :manage, :admin)
			%li.btnNombre
				= link_to t('common.admin.users'), users_path
		%li.btnNombre
			= link_to current_user.to_s, user_path(current_user)

		%li.btnNombre
			= link_to "Home", home_path
		%li.btnsalir 
			= link_to t('common.nav.logout'), log_out_path
	- else
		%li.btnNombre 
			= link_to t('common.nav.login'), log_in_path, :class => 'needs-login'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %link{:rel=>"icon", :type => "image/ico", :href => "/assets/favicon.ico"}
      %title= content_for?(:title) ? yield(:title) : t('common.app_name')
      %meta{:content => content_for?(:description) ? yield(:description) : t('common.app_desc'), :name => "description"}
      = metamagic
      = stylesheet_link_tag "application", :media => "all" #, "data-turbolinks-track" => true
      = javascript_include_tag "application" #, "data-turbolinks-track" => true
      = csrf_meta_tags
      = yield(:head)

      -# Mobile First
      %meta{name: "viewport", content:"width=device-width, initial-scale=1"}
      
      -# Google Analytics
        :javascript
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-XXXXXX-X', 'dominio.cl');
          ga('send', 'pageview');

      -# Metatags para Facebook y Twitter
        %link{ :rel => "image_src",  :href => "/assets/logocuadrado.png" }
        %meta{ :property=>"og:image" , :content=>"/assets/logocuadrado.png" }
        %meta{ :property=>"og:type" , :content=>"company" }
        %meta{ :property=>"og:site_name" , :content=> t('common.app_name') }
        %meta{ :property=>"og:url" , :content=> t('common.app_url') }
        %meta{ :property=>"og:description",  :content=> t('common.app_desc') }
      -# Keywords para google y metatag de verificación de ownership
        %meta{  :name=>"keywords", :content=>"brainshots,brainshots.cl,ingenieria,tecnología,emprendimiento,chile" }
        %meta{ :name=>"google-site-verification", :content=>"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" }

  %body{:class => "#{controller_name} #{action_name}"}
    :javascript
      // https://developers.facebook.com/docs/plugins/comments
      (function(d, s, id) {var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        //js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.3&appId=253929998121241";
        fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
        // ON PAGE LOAD
        setTimeout(function(){
          resizeFacebookComments();
        }, 1000);
        setTimeout(function(){
          resizeFacebookComments();
        }, 2000);
        // ON PAGE RESIZE
        $(window).on('resize', function(){
          resizeFacebookComments();
        });
        function resizeFacebookComments(){
          if($('.fb-comments iframe').length){
            var src   = $('.fb-comments iframe').attr('src').split('width='),
                width = $('.fb-comments').parent().width();
            $('.fb-comments iframe').attr('src', src[0] + 'width=' + width);
          }
        }
    %header{:role => "banner"}
      .navbar-header

    .transition
      .marginMenu
        .slidemenu.visible-xs.alterHeight  
          = render 'layouts/slidemenu'

      .contGeneral.alterHeight    
        -unless @hide_header
          %header{:role => "banner"}
            .navbar-header
              %button.navbar-toggle.fa.fa-bars.visible-xs.slidemenu-trigger{ :type => "button"}
              %a.navbar-brand{:href => home_path}= t('common.app_name')
              %button.navbar-toggle.fa.fa-plus-square-o.btnPlus.visible-xs{"data-target" => ".bs-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              .nav.mainmenu.hidden-xs
                = render 'layouts/navigation'
        .visible-xs
          .marginMenu
          %nav.collapse.navbar-collapse.bs-navbar-collapse.menuExtra{:role => "navigation"}
            = render 'layouts/navigation'





        .container-fluid
          = render 'layouts/messages'
          -unless current_user
            = render partial: "sessions/login"
            = render partial: "sessions/register"
          = yield

      .hidden-xs
        = render 'layouts/footer'
    .visible-xs
      = render 'layouts/footer'